version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: git submodule add https://github.com/0xd4d/dnlib
- cmd: git submodule add https://github.com/0xd4d/de4dot
- cmd: nuget restore "ConfuserEx Dynamic Unpacker.sln"
- cmd: git submodule update --init --recursive
build:
  project: ConfuserEx Dynamic Unpacker.sln
  verbosity: normal
artifacts:
- path: ConfuserEx Dynamic Unpacker\bin
  name: ConfuserEx-Unpacker v%APPVEYOR_BUILD_VERSION%
